### ISSUE TITLE
Are there any pretrained models provided？

### ISSUE THREAD

**Issue by acceleratelch** [fwtan/RerankingTransformer#19]
Want to test on a pretrained model , is there any official pretrained model?

**Comment by acceleratelch** [comment]
> Want to test on a pretrained model , is there any official pretrained model?

Already find on huggingface.

**Comment by fwtan** [comment]
Feel free to re-open the issue if you have any further questions.

**Comment by LynnLing18** [comment]
> > Want to test on a pretrained model , is there any official pretrained model?
> 
> Already find on huggingface.

I also want  pretrained model. Can you give me the link?Thanks!
